services:
  erigon:
    image: ghcr.io/phylayer1/erigon:v2.54.0
    user: root
    restart: unless-stopped
    network_mode: host
    entrypoint: /init-erigon.sh
    port:
      - 8545:8545 
    volumes:
      - ./data:/data
      - ./config:/config
      - "./init-erigon.sh:/init-erigon.sh"
    command:
      - --datadir=/data/erigon
      - --bootnodes=enode://0c5ec541f147a349bfd3a0eaae009d6bcaf82600406587baac9e0e9b58dea83ce53b11e065e74bde29c102d0c594a0105681bd6e93daf6e98382a91c72a29004@119.59.96.81:30303,enode://5ad2fbac466cb4ab3004f1170ed81dbf676f77cbc6c9521355e9f2382a919e78a7a862cb6e816ac6b12017f956e0e1a879d2b82956f65ab93dbc74deba504469@135.181.41.146:30303
      - --staticpeers=enode://0c5ec541f147a349bfd3a0eaae009d6bcaf82600406587baac9e0e9b58dea83ce53b11e065e74bde29c102d0c594a0105681bd6e93daf6e98382a91c72a29004@119.59.96.81:30303,enode://5ad2fbac466cb4ab3004f1170ed81dbf676f77cbc6c9521355e9f2382a919e78a7a862cb6e816ac6b12017f956e0e1a879d2b82956f65ab93dbc74deba504469@135.181.41.146:30303
      - --networkid=7
      - --ws
      - --http
      - --http.addr=0.0.0.0
      - --http.api=eth,engine,erigon,web3,net,debug,trace,txpool,ots
      - --authrpc.addr=0.0.0.0
      - --authrpc.port=8551
      - --authrpc.vhosts=*
      - --authrpc.jwtsecret=/config/jwt.hex

  lighthouse:
    image: ghcr.io/phylayer1/lighthouse-v1
    user: root
    network_mode: host
    volumes:
      - ./data/lighthouse:/root/.lighthouse
      - ./data/erigon:/data/:ro
      - ./config:/config
    command:
      - lighthouse
      - beacon
      - --execution-endpoint=http://127.0.0.1:8551
      - --execution-jwt=/config/jwt.hex
      - --testnet-dir=/config
      - --http-allow-sync-stalled
      - --disable-peer-scoring
      - --http
      - --disable-packet-filter
      - --eth1
      - --target-peers=5
#      - --enr-address=xx.xx.xx.xx
      - --enr-udp-port=9000
      - --enr-tcp-port=9000

